// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkzvrtvefhxhpqgwvvhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprenZydHZlZmh4aHBxZ3d2dmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjE0MzEsImV4cCI6MjA2ODU5NzQzMX0.nwlm9FkwGNH5CFvqI-8a3T9lyZ2pfBhjDpErdZPubTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});